import "./globals.css";

export const metadata = {
  title: "My Demo",
  description: "Generated by Parth",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="w-full min-h-screen mx-auto max-w-[1920px] px-4 sm:px-6 md:px-8 lg:px-12">
          {children}
        </div>
      </body>
    </html>
  );
}
